<a href="https://colab.research.google.com/github/m0304s/DeepLearning/blob/main/Lecture1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

a = np.array([2,3,4])

a.shape, a.ndim, a.dtype, a.itemsize, a.size

(2, 3)

In [4]:
b = np.array([[1,2,3],[4,5,6]])
b.shape

(2, 3)

In [5]:
student_mid = np.array([70,85,92,79])
student_fin = np.array([90,65,70,85])

student_sum = student_mid + student_fin

print('중간고사와 기말시험 성적의 합 :', student_sum)

중간고사와 기말시험 성적의 합 : [160 150 162 164]


In [6]:
print('평균 성적 : ',student_sum/2)

평균 성적 :  [80. 75. 81. 82.]


In [8]:
np.array(range(1,11))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.full((2,3),100)

array([[100, 100, 100],
       [100, 100, 100]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
a = np.array([1,2,3])
b = np.array(([4,5,6],[7,8,9]))

np.append(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.append([a],b,axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a = np.array([[1,2],[3,4]])
b = np.array([[10,20],[30,40]])

a * b

array([[ 10,  40],
       [ 90, 160]])

In [19]:
np.matmul(a,b)  #2차원 배열 a,b의 행렬곱, a@b와 같다.

array([[ 70, 100],
       [150, 220]])

In [21]:
a @ b

array([[ 70, 100],
       [150, 220]])

In [23]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]])

print(arr_2d[0][0])
print(arr_2d[2])

1
[7 8 9]


In [24]:
arr_2d[1:][0:2]

array([[4, 5, 6],
       [7, 8, 9]])

In [27]:
length0, length1 = arr_2d.shape

for i in range(length0):
  for j in range(length1):
    print(arr_2d[i][j], arr_2d[i,j])

1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
0 0
1 1
2 2


In [28]:
ages = np.array([28,25,12,16,20])

y = ages>=21

y

array([ True,  True, False, False, False])

In [29]:
age_over21 = ages[ages>=21]
print(f'age_over21 = {age_over21}')

age_over21 = [28 25]


In [30]:
rnd = np.random.randn(5)*10+165

In [33]:
rnd.round(2)

array([160.22, 149.42, 158.99, 168.75, 169.17])

In [34]:
rnd.astype(int)

array([160, 149, 158, 168, 169])

In [35]:
np.random.seed(42)

In [38]:
nums = np.random.normal(loc = 165, scale = 10, size=(3,4)).round(2)
nums

array([[159.56, 166.11, 153.49, 168.76],
       [158.99, 162.08, 158.98, 183.52],
       [164.87, 154.42, 173.23, 152.79]])

In [39]:
a = np.arange(10)
np.random.shuffle(a)
a

array([0, 7, 6, 2, 4, 3, 9, 8, 5, 1])

In [40]:
np.random.permutation([2,4,6,7,10])

array([ 2,  6, 10,  4,  7])

In [41]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [42]:
np.logspace(0,5,10)

array([1.00000000e+00, 3.59381366e+00, 1.29154967e+01, 4.64158883e+01,
       1.66810054e+02, 5.99484250e+02, 2.15443469e+03, 7.74263683e+03,
       2.78255940e+04, 1.00000000e+05])

In [45]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
y.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
y.reshape(-1,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [48]:
y.reshape(-1,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [49]:
a = np.array([1,-4])
b = np.array([3,6])

print('a = ',a)
print('b = ',b)

a =  [ 1 -4]
b =  [3 6]


In [51]:
print('a dot b = ',np.dot(a,b))

a dot b =  -21


In [52]:
print('a dot b = ',a.dot(b))

a dot b =  -21


In [53]:
u = np.array([1,2,0,-1])
v = np.array([2,2,3,4])
print('u dot v = ',np.dot(u,v))

u dot v =  2


In [54]:
a = [[1,2],[3,4]]
b = [[1,0],[0,1]]

np.matmul(a,b)

array([[1, 2],
       [3, 4]])